# Generated by Django 4.2.9 on 2024-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='webapp_prod_price_d0e87a_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['cost'], name='webapp_prod_cost_7a539c_idx'),
        ),
    ]
